name: viam_flutter_provisioning_widget
description: "A Flutter package for provisioning Viam machines using multiple methods."
version: 0.0.1
homepage: https://www.viam.com

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  viam_flutter_bluetooth_provisioning_widget: ^0.0.24
  viam_flutter_hotspot_provisioning_widget: ^0.0.18
  viam_sdk: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

